[package]
name = "deflorta-launcher"
description = "Runs a published Deflorta game from its game.dm archive"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[features]
default = ["dev-console"]
dev-console = ["deflorta/dev-console"]

[dependencies]
deflorta.workspace = true
anyhow.workspace = true
log.workspace = true
clap.workspace = true
deflorta-data.workspace = true
serde_json.workspace = true
