[package]
name = "deflorta-android"
description = "Android export runtime for Deflorta games"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "deflorta_android"
crate-type = ["cdylib"]

[lints]
workspace = true

[target.'cfg(target_os = "android")'.dependencies]
deflorta.workspace = true
anyhow.workspace = true
log.workspace = true
android_logger = "0.15.1"
winit = { version = "0.30.13", features = ["android-game-activity"] }
