// deflorta — the public scripting API. Games import everything from here:
//
//   import { configure, character, label, say, scene, show, menu } from "deflorta";

export { config, configure, log, on, readText, setTimer, clearTimer, storage, command } from "deflorta/core";
export {
  FILL,
  box,
  button,
  hideScreen,
  img,
  invalidate,
  isShown,
  screen,
  screenProps,
  shownScreens,
  replaceScreens,
  showScreen,
  text,
} from "deflorta/ui";
export {
  actions,
  advance,
  at,
  call,
  canSave,
  center,
  character,
  checkpoint,
  defaults,
  deleteSave,
  dissolve,
  endGame,
  fade,
  hide,
  image,
  inGame,
  jump,
  keymap,
  label,
  left,
  loadGame,
  menu,
  moveinleft,
  moveinright,
  moveoutleft,
  moveoutright,
  music,
  newGame,
  pause,
  prefs,
  randInt,
  random,
  right,
  rollback,
  saveGame,
  saveInfo,
  savePrefs,
  say,
  scene,
  show,
  sound,
  store,
  truecenter,
  windowHide,
  zoomin,
} from "deflorta/story";
export { notify } from "deflorta/screens";
