[package]
name = "deflorta-cli"
description = "Command-line tools for Deflorta games"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "deflorta"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
deflorta-data.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
oxc.workspace = true
clap.workspace = true
lz4.workspace = true
