[package]
name = "deflorta-data"
description = "Shared game files, archive format and module resolution for Deflorta"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
serde.workspace = true
log.workspace = true
lz4r.workspace = true
# Same version as for cosmic-text
fontdb = "0.23.0"
symphonia-core = "0.6.1"
