[package]
name = "deflorta"
description = "A visual novel engine scripted in JavaScript"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[features]
debug-formats = ["deflorta-assets/debug-formats"]
dev-console = ["deflorta-engine-core/dev-console", "deflorta-headless/dev-console"]

[dependencies]
deflorta-assets.workspace = true
deflorta-common.workspace = true
deflorta-ui.workspace = true
deflorta-js-bridge.workspace = true
deflorta-engine-core.workspace = true
deflorta-headless.workspace = true
winit.workspace = true
accesskit.workspace = true
accesskit_winit.workspace = true
gilrs.workspace = true
num-traits.workspace = true
pollster.workspace = true
wgpu.workspace = true
anyhow.workspace = true
log.workspace = true
pretty_env_logger.workspace = true

[target.'cfg(target_os = "android")'.dependencies]
winit = { workspace = true, features = ["android-game-activity"] }
