import groovy.json.JsonSlurper

plugins {
    id("com.android.application")
}

// Generated by `deflorta publish`; native runtimes are built independently.
val exportFile = rootProject.file("deflorta-export.json")
val game = if (exportFile.exists()) JsonSlurper().parse(exportFile) as Map<*, *> else mapOf(
    "applicationId" to "org.deflorta.template", "title" to "Deflorta",
    "versionCode" to 1, "versionName" to "0.1.0"
)
val signing = listOf("DEFLORTA_KEYSTORE", "DEFLORTA_KEYSTORE_PASSWORD",
    "DEFLORTA_KEY_ALIAS", "DEFLORTA_KEY_PASSWORD").associateWith { System.getenv(it) }
if (signing.values.any { !it.isNullOrEmpty() } && signing.values.any { it.isNullOrEmpty() }) {
    throw GradleException("Set all four DEFLORTA signing environment variables")
}

android {
    namespace = "org.deflorta.android"
    compileSdk = 36
    defaultConfig {
        applicationId = game["applicationId"] as String
        minSdk = 26
        targetSdk = 36
        versionCode = (game["versionCode"] as Number).toInt()
        versionName = game["versionName"] as String
        // A placeholder handles arbitrary Unicode titles without generated XML.
        manifestPlaceholders["gameTitle"] = game["title"] as String
    }
    signingConfigs {
        create("release") {
            signing["DEFLORTA_KEYSTORE"]?.takeIf { it.isNotEmpty() }?.let {
                storeFile = File(it)
                storePassword = signing["DEFLORTA_KEYSTORE_PASSWORD"]
                keyAlias = signing["DEFLORTA_KEY_ALIAS"]
                keyPassword = signing["DEFLORTA_KEY_PASSWORD"]
            }
        }
    }
    buildTypes {
        release {
            isMinifyEnabled = true
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
            if (!signing["DEFLORTA_KEYSTORE"].isNullOrEmpty()) {
                signingConfig = signingConfigs.getByName("release")
            }
        }
    }
    androidResources {
        noCompress += "dm"
    }
    packaging {
        jniLibs {
            useLegacyPackaging = false
            // Native templates already strip debug info; exporting needs no NDK.
            keepDebugSymbols += "**/*.so"
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
}

dependencies {
    // Matches android-activity 0.6.1's bundled native glue. No prefab/CMake build.
    implementation("androidx.games:games-activity:4.4.0")
    implementation("androidx.appcompat:appcompat:1.8.0")
}
